//|===========================================================================
//|  Team Name: Compiler Builders 33
//|
//|  Programmers:
//|		Cristen Palmer
//|		Megan Chipman
//|		Jason Lancaster
//|		Victoria Proetsch
//|
//|  Course:	COP3402, Fall 2016
//|  Date:      Oct 6, 2016
//|---------------------------------------------------------------------------
//|  Language:	C
//|  File:		driver.c
//|  Purpose:	attends to the overall flow of the lexer, parser,
//|             code gen, and running of code on the vm.
//|
//|  Notes:
//|===========================================================================

//Included Libraries
#include <stdio.h>
#include <stdlib.h>
#include "tokens.h"
#include "error.h"
#include "lexer.h"

int main() {

    //Declare and Initialize Variables:
    extern aToken_type *tok;

    //Open and Declare File Pointers:
    FILE *source;
    FILE *clean;

    source = fopen("tester.txt", "r");
    clean = fopen("clean.pl0", "w");

    //Check if pointers are valid:
    if (source == NULL){
        printf("Unable to open file.\n");
    }

    if (clean == NULL){
        printf("Unable to open file.\n");
    }

    //Remove Comments from Source File:
    removeComments(source, clean);

    //close file pointers
    fclose(source);
    fclose(clean);

    //Have Clean point to the new, clean file:
    clean = fopen("clean.pl0", "r");

    //run the lexer
    do_lex(clean);

    //this while loop just prints the tokArr generated by the lexer to check for validity
    while(true)
    {
        //Get the tokens from the shared array of tokens generated by lexer
        tok = nextToken();

        //make sure tok is valid
        if (tok == NULL){
            printf("invalid token\n");
            break;
        }

        // halt if nullsym is returned
        if ( tok->t == 1 )
            break;

        //Display the appropriate token
        //printf("token: ");
        displayToken(tok);
        //printf("\n");
    }
    printf("\n");

    //Back to the beginning
    tok = rewindParseTokens();

    //run the parser
    program();

    //Close the cleanFile pointer
    fclose(clean);
}
